- hosts: all
  gather_facts: true
  become: true

  tasks:
    - block:
      - yum:
          name: epel-release
          state: latest

      - yum:
          name: nginx
          state: latest

      - systemd:
          name: nginx
          state: started
          enabled: yes
